name: build

on:
  push:
    branches-ignore:
      - dev
  pull_request:
    branches-ignore:
      - dev

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        preset: [Release]
    runs-on: ${{ matrix.os }}
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    - name: Fix git safe directory
      run: git config --global --add safe.directory "${{ github.workspace }}"

    # fetch latest cmake
    - uses: lukka/get-cmake@v3.31.6

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }} --parallel $(nproc)

    - name: Deploy
      if: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' }}
      uses: actions/upload-artifact@master
      with:
        name: sphaira-${{ matrix.preset }}
        path: build/${{ matrix.preset }}/sphaira.nro
